/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DocumentationRequest {
  'id' : string,
  'status' : DocumentationRequestStatus,
  'uploadedDocuments' : Array<ExternalBlob>,
  'mode' : string,
  'fullName' : string,
  'mobileNumber' : string,
  'message' : string,
  'timestamp' : bigint,
  'serviceNeeded' : string,
}
export type DocumentationRequestStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export type ExternalBlob = Uint8Array;
export interface Product {
  'id' : string,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'discount' : bigint,
  'category' : string,
  'rating' : number,
  'price' : number,
  'images' : Array<ExternalBlob>,
}
export interface StudentLead {
  'id' : string,
  'status' : string,
  'additionalNotes' : string,
  'studentName' : string,
  'subjectsRequired' : string,
  'mode' : string,
  'submittedAt' : bigint,
  'preferredTime' : string,
  'contactNumber' : string,
  'budget' : bigint,
  'classOrCourse' : string,
  'location' : string,
}
export interface TeacherRegistration {
  'id' : string,
  'status' : string,
  'classesTeach' : string,
  'subjectsTeach' : string,
  'idProofUrl' : string,
  'mode' : string,
  'fullName' : string,
  'submittedAt' : bigint,
  'mobileNumber' : string,
  'photoUrl' : string,
  'email' : string,
  'experienceYears' : bigint,
  'expectedFees' : bigint,
  'qualification' : string,
  'location' : string,
}
export interface UpdateProductRequest {
  'id' : string,
  'stockQuantity' : bigint,
  'name' : string,
  'description' : string,
  'discount' : bigint,
  'category' : string,
  'rating' : number,
  'price' : number,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDocumentationRequest' : ActorMethod<
    [string, string, string, string, Array<ExternalBlob>, string],
    undefined
  >,
  'createProduct' : ActorMethod<[Product], undefined>,
  'customQueryExample' : ActorMethod<[bigint], bigint>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllStudentLeads' : ActorMethod<[], Array<StudentLead>>,
  'getAllTeacherRegistrations' : ActorMethod<[], Array<TeacherRegistration>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDocumentationRequestDocuments' : ActorMethod<
    [string],
    Array<ExternalBlob>
  >,
  'getDocumentationRequests' : ActorMethod<[], Array<DocumentationRequest>>,
  'getProduct' : ActorMethod<[string], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitStudentLead' : ActorMethod<[StudentLead], string>,
  'submitTeacherRegistration' : ActorMethod<[TeacherRegistration], string>,
  'updateDocumentationRequestStatus' : ActorMethod<
    [string, DocumentationRequestStatus],
    undefined
  >,
  'updateProduct' : ActorMethod<[UpdateProductRequest], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];