/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'discount' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
  'images' : IDL.Vec(ExternalBlob),
});
export const StudentLead = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'additionalNotes' : IDL.Text,
  'studentName' : IDL.Text,
  'subjectsRequired' : IDL.Text,
  'mode' : IDL.Text,
  'submittedAt' : IDL.Int,
  'preferredTime' : IDL.Text,
  'contactNumber' : IDL.Text,
  'budget' : IDL.Nat,
  'classOrCourse' : IDL.Text,
  'location' : IDL.Text,
});
export const TeacherRegistration = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'classesTeach' : IDL.Text,
  'subjectsTeach' : IDL.Text,
  'idProofUrl' : IDL.Text,
  'mode' : IDL.Text,
  'fullName' : IDL.Text,
  'submittedAt' : IDL.Int,
  'mobileNumber' : IDL.Text,
  'photoUrl' : IDL.Text,
  'email' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'expectedFees' : IDL.Nat,
  'qualification' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const DocumentationRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const DocumentationRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : DocumentationRequestStatus,
  'uploadedDocuments' : IDL.Vec(ExternalBlob),
  'mode' : IDL.Text,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'serviceNeeded' : IDL.Text,
});
export const UpdateProductRequest = IDL.Record({
  'id' : IDL.Text,
  'stockQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'discount' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDocumentationRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(ExternalBlob), IDL.Text],
      [],
      [],
    ),
  'createProduct' : IDL.Func([Product], [], []),
  'customQueryExample' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllStudentLeads' : IDL.Func([], [IDL.Vec(StudentLead)], ['query']),
  'getAllTeacherRegistrations' : IDL.Func(
      [],
      [IDL.Vec(TeacherRegistration)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDocumentationRequestDocuments' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExternalBlob)],
      ['query'],
    ),
  'getDocumentationRequests' : IDL.Func(
      [],
      [IDL.Vec(DocumentationRequest)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitStudentLead' : IDL.Func([StudentLead], [IDL.Text], []),
  'submitTeacherRegistration' : IDL.Func([TeacherRegistration], [IDL.Text], []),
  'updateDocumentationRequestStatus' : IDL.Func(
      [IDL.Text, DocumentationRequestStatus],
      [],
      [],
    ),
  'updateProduct' : IDL.Func([UpdateProductRequest], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'discount' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
    'images' : IDL.Vec(ExternalBlob),
  });
  const StudentLead = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'additionalNotes' : IDL.Text,
    'studentName' : IDL.Text,
    'subjectsRequired' : IDL.Text,
    'mode' : IDL.Text,
    'submittedAt' : IDL.Int,
    'preferredTime' : IDL.Text,
    'contactNumber' : IDL.Text,
    'budget' : IDL.Nat,
    'classOrCourse' : IDL.Text,
    'location' : IDL.Text,
  });
  const TeacherRegistration = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'classesTeach' : IDL.Text,
    'subjectsTeach' : IDL.Text,
    'idProofUrl' : IDL.Text,
    'mode' : IDL.Text,
    'fullName' : IDL.Text,
    'submittedAt' : IDL.Int,
    'mobileNumber' : IDL.Text,
    'photoUrl' : IDL.Text,
    'email' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'expectedFees' : IDL.Nat,
    'qualification' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DocumentationRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const DocumentationRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : DocumentationRequestStatus,
    'uploadedDocuments' : IDL.Vec(ExternalBlob),
    'mode' : IDL.Text,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'serviceNeeded' : IDL.Text,
  });
  const UpdateProductRequest = IDL.Record({
    'id' : IDL.Text,
    'stockQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'discount' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDocumentationRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(ExternalBlob),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createProduct' : IDL.Func([Product], [], []),
    'customQueryExample' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllStudentLeads' : IDL.Func([], [IDL.Vec(StudentLead)], ['query']),
    'getAllTeacherRegistrations' : IDL.Func(
        [],
        [IDL.Vec(TeacherRegistration)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDocumentationRequestDocuments' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExternalBlob)],
        ['query'],
      ),
    'getDocumentationRequests' : IDL.Func(
        [],
        [IDL.Vec(DocumentationRequest)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Text], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitStudentLead' : IDL.Func([StudentLead], [IDL.Text], []),
    'submitTeacherRegistration' : IDL.Func(
        [TeacherRegistration],
        [IDL.Text],
        [],
      ),
    'updateDocumentationRequestStatus' : IDL.Func(
        [IDL.Text, DocumentationRequestStatus],
        [],
        [],
      ),
    'updateProduct' : IDL.Func([UpdateProductRequest], [], []),
  });
};

export const init = ({ IDL }) => { return []; };